const navLink = {
  dashboard: "/dashboard",
  orders: "/dashboard/orders",
  ordersList: "/dashboard/ordersList",
  billing: "/dashboard/billing",
  kitchen: "/dashboard/kitchen",
  tables: "/dashboard/tables",
  qrOrders: "/dashboard/qr-orders",
  menus: "/dashboard/menus",
  inventory: "/dashboard/inventory",
  inventoryStock: "/dashboard/inventory/stock",
  inventoryRecipes: "/dashboard/inventory/recipes",
  inventoryPurchases: "/dashboard/inventory/purchases",
  inventoryStockCount: "/dashboard/inventory/stock-count",
  inventoryWarehouse: "/dashboard/inventory/warehouse",
  inventoryTransfers: "/dashboard/inventory/transfers",
  inventoryWastage: "/dashboard/inventory/wastage",
  inventoryProduction: "/dashboard/inventory/production",
  inventoryVarianceReport: "/dashboard/inventory/variance-report",
  reports: "/dashboard/reports",
  restaurantProfile: "/dashboard/restaurant-profile",
  branchManagement: "/dashboard/branch-management",
  staff: "/dashboard/staff",
  staffMyTeam: "/dashboard/staff/my-team",
  staffRoster: "/dashboard/staff/roster",
  staffAttendance: "/dashboard/staff/attendance",
  staffEarnings: "/dashboard/staff/earnings",
  customers: "/dashboard/customers",
  loyaltySettings: "/dashboard/settings/loyalty",
  appearance: "/dashboard/appearance",
  privileges: "/dashboard/privileges",
  settings: "/dashboard/settings",
  owner: "/dashboard/owner",
  ownerAddRestaurant: "/dashboard/owner/add-restaurant",
};

export { navLink };
